### ISSUE TITLE
@auth doesn't work in python3 because of comparison bytes with str

### ISSUE THREAD

**Issue by ben-xo** [thisissoon/djangohmac#25]
sign.py calls `get_signature(request)` and passes it to `validate_multiple_signatures()`, which calls `make_hmac_for(key, body)`. Unfortunately, the signature from `get_signature` is a string, whilst the signature from `make_hmac_for()` is a byte array.

The workaround is to cast them both to byte arrays with `six.b()` right before the comparison, otherwise they comparison always fails.

**Comment by jamesjwarren** [comment]
Fixed in #26
