### ISSUE TITLE
Ability to configure Status Code

### ISSUE THREAD

**Issue by krak3n** [thisissoon/djangohmac#5]
It would be cool if we could configure the status code we send in responses for requests that fail. The SOON_ API Spec defines it should be a `400` since `401` and `403` are reserved for use with user authentication.

I propose a `HMAC_REJECT_CODE`which is defaulted to `403`

What do you think @radeklos?

**Comment by radeklos** [comment]
@krak3n sounds good. Atm middleware raises `PermissionDenied` exception. We can configure an exception which will be raised in middleware.. I quickly took a look into Djagno handler and `SuspiciousOperation` returns 400.

**Comment by krak3n** [comment]
Ah ok we have to throw exceptions, so `HMAC_EXCEPTION` then?

**Comment by krak3n** [comment]
@radeklos I would like to get this sorted soon since it makes it much easier to differentiate a HMAC failed request and one which is just an un authenticated one.

Happy to implement if you are busy on other things?

**Comment by radeklos** [comment]
problem is that current `abort` function raises permission exception which is caught by django handlers..  django really cannot decorate drf views and documentation recommend to wrap routes instead - where custom requests can be applied.

**Comment by krak3n** [comment]
can we get the middleware to return a `django.http.response.HttpResponseBadRequest` rather than throwing an exception?

**Comment by radeklos** [comment]
middleware also covers request to the admin but we usually split the admin and app to different boxes..

**Comment by krak3n** [comment]
Yes, the Admin will run with HMAC checks disabled.
